language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
    - flags="-o"
    - composer install $flags
    - cp phpunit.xml.dist phpunit.xml

script: phpunit
